### ISSUE TITLE
boost not recognized in fedora 33 installation with ns-3

### ISSUE THREAD

**Issue by omarchakroun** [ERIGrid/ns3-fmi-export#2]
i have been trying to install this package along with ns3.27 under fedora33. the ns3 part works fine but when it try to recompile it with the options related to fmi-export using waf i got an error that boost installation is not found. do you recommend any version of boost ? and is there any workaround for this issue that you know of?
thank you and best regards,
omar

**Comment by omarchakroun** [comment]
I think the issue is related to the boost version that i was using, i was using the version 1.73 but after downgrading to the version 1.66 the problem was solved. I think the issue is related to the inexistance of signals library in the newer boost version (after 1.68) and its replacement with signals2 and that your .pyc library is making a call to the former and since it doesnt exist it will not recognize boost installation at all.

**Comment by ewidl** [comment]
Thank you for investigating this issue!

I have updated the README file accordingly, see commit cab2af06a63bb4788c33a21cb615d79d90db9f17.
