### ISSUE TITLE
fmi export usage

### ISSUE THREAD

**Issue by omarchakroun** [ERIGrid/ns3-fmi-export#3]
i'm trying to find out if the export package will be usefull for a particular case. i need to export the ns3 simulation model using the fmi-export package and make it work under windows platform. do i have to use the linux based installation and will have the choice to select the target platform for its deployment or use the cygwin based installation in order for it to work under windows?
thank you and best regards,
omar

**Comment by ewidl** [comment]
The exported FMU implements a so-called "tool coupling approach". This means that the FMU connects at runtime to the installed ns-3 application. Hence, when you compile an ns-3 FMU under Linux, it will not work on Windows.

Unfortunately, ns-3 support for Windows is quite limited (or at least is was when this package was developed). However, one option to make it run is by using Cygwin. When done properly, this approach even allows to combine ns-3 FMUs with other Windows applications in a co-simulation (see for instance [here](https://github.com/ERIGrid/JRA2-TC3)).
