### ISSUE TITLE
unable to run SimpleFMU example

### ISSUE THREAD

**Issue by omarchakroun** [ERIGrid/ns3-fmi-export#4]
Hi,
i'm trying to make the SimpleFMU example work under cygwin using the ns-dev version. i got an issue when running the basic example due to the fact that the JSON file generation was not successfull
[ERROR] generation of JSON file failed (execution failed).

have you any idea what can cause that ?
thank you,
Omar

**Comment by omarchakroun** [comment]
The issue seems to be coming from using cygwin 64 bits version. going to cygwin32 bit version and downgrading to ns3.30 solved the issue related to this JSON file creation.

**Comment by ewidl** [comment]
I can verify that ns-3 installations on 64-bit versions of Cygwin do not work. ns-3 compiles without errors, but when running an executable it crashes instantly with a segmentation violation. This is unrelated to the FMI export module, it even happens with the simplest ns-3 example (e.g., the ``scratch-simulator``). This same issue causes the error you saw. 

The latest version of the FMI export module is also not compatible with the latest version of ns-3-dev (see issue #1). Hence, switching to an older version was the correct choice.

I am currently working on making the FMI export module work with the latest ns-3-dev version. I am quite confident that I will finish this quite soon. However, I added a [new branch](https://github.com/ERIGrid/ns3-fmi-export/tree/ns-3.29) with specific installation instructions for ns-3.29, which was the version this package was developed for.
